### ISSUE TITLE
Install & run dstat

### ISSUE THREAD

**Issue by EmilienM** [redhat-openstack/tripleo-quickstart#13]
When running tripleo-quickstart in a CI environment, it can be useful to get live systems informations.
`dstat` is an excellent tool for that, OpenStack CI already uses it. 

``` bash
sudo dnf -y install dstat
sudo dstat -tcmndrylpg --top-cpu-adv --top-io-adv --nocolor | sudo tee --append /var/log/dstat.log > /dev/null &
```

**Comment by trown** [comment]
moved to https://bugs.launchpad.net/tripleo-quickstart/+bug/1571044
