### ISSUE TITLE
All package lists should be variables (defaulted)

### ISSUE THREAD

**Issue by trown** [redhat-openstack/tripleo-quickstart#15]
This is a requirement of cross-distro support since packages can be named differently in different distros.

**Comment by larsks** [comment]
I've created #18 to track issues concerning cross-distribution support.

**Comment by trown** [comment]
nice, our first meta-issue.

**Comment by larsks** [comment]
This is actually resolved by https://review.gerrithub.io/#/c/265712/, if that merges.  If not, we can try picking out the relevant bits.

**Comment by trown** [comment]
With the split out of image building I think cross-distro support is more about distros creating an image that would work with tripleo-quickstart. I think we do not have any distro specific things in the image consumption, but if so we can open new launchpad bugs for that.
