### ISSUE TITLE
Need some basic lint CI

### ISSUE THREAD

**Issue by trown** [redhat-openstack/tripleo-quickstart#16]
Things like line length, but could also include some ansible style guidelines.

**Comment by larsks** [comment]
Line length will be a tricky one.

URLs can be long (`http://trunk.rdoproject.org/centos7-liberty/ce/30/ce30250c9e9858aeddb0f65583ceaa8a49fe62b4_a2b13371/diskimage-builder-1.11.1-0.20160217003244.352e58c.el7.centos.noarch.rpm`)

Fully qualified python module names can be long (`nova.virt.baremetal.virtual_power_driver.VirtualPowerManager`).

We would need a way to exempt files or specific lines (comment on preceding line?) from the linting.

**Comment by trown** [comment]
Covered by https://bugs.launchpad.net/tripleo-quickstart/+bug/1571047 for now, we can open more launchpad bugs for future lint-style scripts.
