### ISSUE TITLE
Cross-distribution support

### ISSUE THREAD

**Issue by larsks** [redhat-openstack/tripleo-quickstart#18]
I have a dream...that one day, tripleo-quickstart will be able to run somewhere besides EL7 distributions. 

Anything impacting this topic should refer to this issue.

**Comment by trown** [comment]
With the split out of image building I think cross-distro support is more about distros creating an image that would work with tripleo-quickstart. I think we do not have any distro specific things in the image consumption, but if so we can open new launchpad bugs for that.
