### ISSUE TITLE
Better handling of persistent network configuration

### ISSUE THREAD

**Issue by larsks** [redhat-openstack/tripleo-quickstart#19]
Someone should be able to reboot their virtualization host without completely hosing their underlcoud.  This means that we need to make network configuration, such as host bridges, persistent.

If we're setting everything up as libvirt networks we get this for free (yay!).  If we're mucking about directly with things like `brctl` or `ovs-vsctl` we may be in for sadness and disappointment.

This intersects with both #18 and #10.

**Comment by trown** [comment]
I wonder if we can not use openvswitch at all. That is the only virthost installed package that is not in the CentOS base repos. (We have to install the RDO release repo to get it)

**Comment by larsks** [comment]
I am already working on removing that :).  I don't see any reason why we're using openvswitch and not legacy linux bridges.

**Comment by larsks** [comment]
This is resolved by 38fe2c4e, which removes openvswitch, ensures persisent bridge configuration by leveraging libvirt, and makes it easier to specify the network configuration.
