### ISSUE TITLE
We should use the `package` module consistently

### ISSUE THREAD

**Issue by larsks** [redhat-openstack/tripleo-quickstart#20]
In order to make #15 not completely crazy we need to use the `package` module exclusively for package installation.  We're still using `yum` in a few places (we're using both in the same role in at least one place).

**Comment by trown** [comment]
With the split out of image building I think cross-distro support is more about distros creating an image that would work with tripleo-quickstart. I think we do not have any distro specific things in the image consumption, but if so we can open new launchpad bugs for that.
