### ISSUE TITLE
Introspection is not being run in CI

### ISSUE THREAD

**Issue by trown** [redhat-openstack/tripleo-quickstart#21]
In the refactor of the CI playbooks, introspection was inadvertently dropped from the nonHA job. This allowed the IPA ramdisk we build in CI to stop working for introspection. (I am pretty sure we are just missing the python-hardware dependency)

We need to make sure to include introspection on at least one job.

**Comment by apevec** [comment]
How did it work in the HA, are nonHA and HA not using the same ironic ramdisk images?

**Comment by apevec** [comment]
@trown  ramdisk error reported in https://github.com/redhat-openstack/tripleo-quickstart/issues/14#issuecomment-192739594
was "failed to run hardware-detect utility: [Errno 2] No such file or directory"
and related journal ends with:

```
Mar 05 15:19:31 localhost ironic-python-agent[1639]: Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
```

So it's not just missing dep, but that ipmi is assumed which doesn't exist in virt nodes?

**Comment by trown** [comment]
will be fixed by https://review.gerrithub.io/#/c/265850/

**Comment by trown** [comment]
fixed, introspection runs in the nonha job.
