### ISSUE TITLE
Thinking about the tripleo-quickstart workflow

### ISSUE THREAD

**Issue by larsks** [redhat-openstack/tripleo-quickstart#23]
I was thinking about workflow today and [this](https://github.com/larsks/oooq-workflow), and in particular:

![](https://raw.githubusercontent.com/larsks/oooq-workflow/master/workflow.png)

The stuff in green in that diagram should be runnable as a completely unprivileged user.  Ideally, if you have a host that is already virt capable and a couple of configured bridges you could just run the playbooks against `localhost` with a `local` connection and end up with a fully deployed overcloud.

I am interested in opinions on the above, and in particular whether or not the `provision` role as described makes sense, and whether it needs an `unprovision` counterpart.

**Comment by trown** [comment]
This is great! I think the provision role as described makes sense, and does not need an unprovision role.

**Comment by larsks** [comment]
It got one anyway :).  https://review.gerrithub.io/#/c/265712/15/playbooks/roles/provision/teardown/tasks/main.yml

**Comment by larsks** [comment]
This is resolved by https://review.gerrithub.io/#/c/265712/
