### ISSUE TITLE
Requires jinja2 2.8 which is not packaged in CentOS

### ISSUE THREAD

**Issue by ghost** [redhat-openstack/tripleo-quickstart#26]
There is (at least) one dependency on a new jinja2.8 functionality, which leads to the following error when the system jinja2 is used (python-jinja2-2.7.2-2.el7.noarch):

TASK [setup/overcloud_nodes : define baremetal vms] ****************************
Thursday 10 March 2016  13:42:25 +0200 (0:00:03.792)       0:00:43.142 *******\* 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TemplateRuntimeError: no test named 'equalto'
fatal: [host0]: FAILED! => {"failed": true, "stdout": ""}

It would be nice if the playbooks could work with the system-provided jinja2.

**Comment by trown** [comment]
It looks like we just recently picked up the 2.8 only feature, but I am not sure there is a better way to do this:

https://github.com/redhat-openstack/tripleo-quickstart/blob/master/playbooks/roles/libvirt/setup/overcloud_nodes/templates/baremetalvm.xml.j2#L28-L34

We don't want the external network directly attached to the fake baremetal VMs.

**Comment by larsks** [comment]
We can ship custom tests in a `test_plugins` directory.  I'll put that together as soon as I can.

**Comment by larsks** [comment]
https://review.gerrithub.io/265838
