### ISSUE TITLE
quickstart requires passwordless SSH access to the host

### ISSUE THREAD

**Issue by joehakimrahme** [redhat-openstack/tripleo-quickstart#27]
I can `ssh root@$VIRTHOST` and login by inputting my password. However `bash quickstart.sh $VIRTHOST` will fail.

If I set up key authentication for SSH, then quickstart.sh will work correctly.

**Comment by trown** [comment]
I think this is really a requirement of ansible with remote connections. We would lose the automated nature if each connection required the password to be typed.

For the case where we run against localhost, we want to be using a local connection, and should not need SSH at all.
