### ISSUE TITLE
Add a ci test for teardown operations

### ISSUE THREAD

**Issue by larsks** [redhat-openstack/tripleo-quickstart#30]
We're currently running teardown tasks against a "clean" system, so there's nothing to tear down.  We should have job that:
- Gets as far as starting the undercloud
- Cleans everything up (libvirt/teardown and envrionment/teardown)
- Re-provisions and boots the undercloud

**Comment by larsks** [comment]
If we add a teardown test, maybe we can remove some of the superfluous teardown roles from the minimal.yml playbook so that it's a little bit more of a useful example.

**Comment by larsks** [comment]
Can we feed one job the output of another jenkins job?  That is, can we configure a teardown test that runs after one of the deploy gate tests and acts on that environment?

**Comment by trown** [comment]
I think we can track this as part of https://bugs.launchpad.net/tripleo-quickstart/+bug/1570289
