### ISSUE TITLE
We should test quickstart.sh in CI

### ISSUE THREAD

**Issue by larsks** [redhat-openstack/tripleo-quickstart#32]
We should test quickstart.sh -- and quickstart.yml -- in CI, since this is what we expose to people.

**Comment by apevec** [comment]
Partial fix https://review.gerrithub.io/265850

**Comment by trown** [comment]
resolved by https://github.com/redhat-openstack/tripleo-quickstart/commit/389d2e9af6eb3fa00fc5096246de33b71279e3a5
