### ISSUE TITLE
Script is not able to deal with switched parameters [notabug]

### ISSUE THREAD

**Issue by fhubik** [redhat-openstack/tripleo-quickstart#34]
This is probably not a bug, but maybe suggestion for improvement in future:

According to documentation, one has to call script following way:
bash quickstart.sh -u $UNDERCLOUD_QCOW2_LOCATION $VIRTHOST

I know even help says:
quickstart.sh: usage: quickstart.sh [options] virthost [release]
...

But I was accidently able to issue:
bash quickstart.sh $VIRTHOST -u $UNDERCLOUD_QCOW2_LOCATION

which failed with error
TASK [setup/undercloud : get undercloud image expected checksum] ***************
task path: /root/.quickstart/tripleo-quickstart/playbooks/roles/libvirt/setup/undercloud/tasks/fetch_image.yml:14
Friday 11 March 2016  11:20:55 +0100 (0:00:00.176)       0:00:20.002 **********
fatal: [host0]: FAILED! => {"changed": true, "cmd": ["curl", "-sf", "https://ci.centos.org/artifacts/rdo/images/-u/delorean/stable/undercloud.qcow2.md5"], "delta": "0:00:00.518934", "
end": "2016-03-11 11:20:55.796695", "failed": true, "invocation": {"module_args": {"_raw_params": "**curl -sf https://ci.centos.org/artifacts/rdo/images/-u/delorean/stable/undercloud.qcow2.md5**", "_uses_shell": false, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 22, "start": "2016-03-11 11:20:55.
277761", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": ["Consider using get_url module rather than running curl"]}

I assume parameter url (with incorrect "-u" inside) was not propagated correctly from bash as he didn't exactly expect different param order.

**Comment by trown** [comment]
I would definitely entertain a patch that fixed this, but I think it is not really a bug since the help gives the correct syntax.

**Comment by trown** [comment]
moved to: https://bugs.launchpad.net/tripleo-quickstart/+bug/1571033
