### ISSUE TITLE
Undercloud post install fails if flavors already exist

### ISSUE THREAD

**Issue by larsks** [redhat-openstack/tripleo-quickstart#39]
In `undercloud-install-post.sh`, we attempt to avoid failures by deleting flavors before (re-)creating them, like this:

```
openstack flavor delete oooq_{{ name }} > /dev/null 2>&1 || true
openstack flavor create --id auto ... oooq_{{ name }}
```

But what actually happens is that the post-install script fails with:

```
+ openstack flavor create --id auto --ram 4096 --disk 49 --vcpus 1 oooq_control
Flavor with name oooq_control already exists. (HTTP 409) (Request-ID: req-55b34a97-f21d-41fd-b69d-e46829811e6c)
```

Because:

```
$ openstack flavor delete oooq_control
public endpoint for messaging service not found
```

This looks like it's due to a bug in python-zaqarclient.

**Comment by larsks** [comment]
This is due to https://bugzilla.redhat.com/show_bug.cgi?id=1317567

**Comment by trown** [comment]
resolved by https://github.com/redhat-openstack/tripleo-quickstart/commit/1328bd7b0daf2b7d31f76364e174b657a64fec75
