### ISSUE TITLE
Generate names in instackenv.json

### ISSUE THREAD

**Issue by dtantsur** [redhat-openstack/tripleo-quickstart#40]
TripleO understand "name" field for nodes in instackenv.json. It's much easier to refer to nodes by e.g. node-%d (the same as devstack btw) than by their UUID.

**Comment by larsks** [comment]
Implementation proposed in https://review.gerrithub.io/266159

**Comment by trown** [comment]
fixed in https://github.com/redhat-openstack/tripleo-quickstart/commit/e3fd24f081b2f4035e009d28f38c7508e716509b
