### ISSUE TITLE
Interrupting quickstart.sh results in erroneous output

### ISSUE THREAD

**Issue by larsks** [redhat-openstack/tripleo-quickstart#41]
If one interrupts `quickstart.sh` via `^C`, it will erroneously display the help output re: how to log in to the undercloud and continue the deploy.  Need to figure out why the `^C` is resulting in failure code from `ansible-playbook` (which would then cause the script to exit because of our `set -e`).

**Comment by trown** [comment]
moved to https://bugs.launchpad.net/tripleo-quickstart/+bug/1571032
