### ISSUE TITLE
Add a default .ssh/config on the undercloud

### ISSUE THREAD

**Issue by mbaldessari** [redhat-openstack/tripleo-quickstart#44]
It would be quite nice to have a .ssh/config for the stack user on the undercloud so that hopping on the
nodes manually is a bit quicker for the senile amongst us:
Host 192.0.2.*
    User heat-admin
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null

**Comment by larsks** [comment]
The fact that ssh doesn't understand CIDR notation is annoying.  It means that any address-based patterns will be too broad if the overcloud network is smaller than a /24.
- We don't know the overcloud address range until we start running the `tripleo/overcloud` role.  
- We don't know specific addresses until _after_ the overcloud deploy is complete.  
- The overcloud hostnames have nothing to do with the node names we use in our configuration.

This means that we really can only do this after the deploy is complete, and we probably need to query nova to figure out which servers have been created.  This information isn't currently exposed in the `overcloud` heat stack.

**Comment by trown** [comment]
resolved by https://github.com/redhat-openstack/tripleo-quickstart/commit/11f9b5cd75827509958743939ee1903e69ef580e
