### ISSUE TITLE
publish: allow arbitrary location + key (vs. hard coded)

### ISSUE THREAD

**Issue by halcyondude** [redhat-openstack/tripleo-quickstart#45]
Presently the publish playbook has hard coded destination.  To make this useful in other contexts (downstream ospd-based image generation in my specific case) we should make this more re-usable.  
WIP to address: https://review.gerrithub.io/#/c/266245/

**Comment by halcyondude** [comment]
https://review.gerrithub.io/#/c/266245/ is failing in CI (due to unrelated CI issues).  Testing with this locally in the meantime.

**Comment by halcyondude** [comment]
Merged: https://github.com/redhat-openstack/tripleo-quickstart/commit/97933f8e813528434fede3aa3779f8d188b4039c

@trown Should I close this?  Not sure on process...

**Comment by trown** [comment]
@halcyondude ya closing the issue when the fix is merged (with comment to the fix) is cool. Note bug process is soon changing to upstream launchpad, but we will add docs for it.
