### ISSUE TITLE
virsh pool-undefine oooq_pool seems to fail from time to time

### ISSUE THREAD

**Issue by mbaldessari** [redhat-openstack/tripleo-quickstart#46]
fatal: [host0]: FAILED! => {"changed": true, "cmd": ["virsh", "pool-undefine", "oooq_pool"], "d
elta": "0:00:00.029126", "end": "2016-03-15 18:23:19.744160", "failed": true, "invocation": {"m
odule_args": {"_raw_params": "virsh pool-undefine \"oooq_pool\"", "_uses_shell": false, "chdir"
: null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "co
mmand"}, "rc": 1, "start": "2016-03-15 18:23:19.715034", "stderr": "error: Failed to undefine p
ool oooq_pool\nerror: internal error: no config file for oooq_pool", "stdout": "", "stdout_line
s": [], "warnings": []}                                                                        

A "rm -rf /run/user/1003/libvirt/" on the host, fixes it

**Comment by mbaldessari** [comment]
I seem to be hitting this more often than not. Here is a full log of a run that gave the error. I assume something
is not always cleaning up the env fully?

http://acksyn.org/files/tripleo/mrg-08.txt

**Comment by larsks** [comment]
If you can reliably reproduce this behavior, I would love to take a closer look at your system.  I suspect a libvirt bug, but I haven't been able to reproduce this behavior myself (but somebody else has seen it).

**Comment by larsks** [comment]
Hey @mbaldessari , we tracked it down: https://www.redhat.com/archives/libvirt-users/2016-March/msg00123.html

https://review.gerrithub.io/#/c/270281/ is an attempt to work around the problem.

**Comment by mbaldessari** [comment]
Nice @larsks, thanks for tracking it down. I owe you coffee ;)
