### ISSUE TITLE
Baremetal support

### ISSUE THREAD

**Issue by mbaldessari** [redhat-openstack/tripleo-quickstart#48]
Let's track here the work needed to get initial baremetal support going:
- Focus initially on a virtual undercloud deployed in a VM which will deploy baremetal nodes
- Need to make the instackenv.json file overridable, so it can be passed to quickstart.sh
- Networking will need to be customizable

**Comment by trown** [comment]
moved to https://bugs.launchpad.net/tripleo-quickstart/+bug/1571028
