### ISSUE TITLE
recent changes invalidate http://blog.oddbit.com/2016/02/19/deploy-an-ha-openstack-development-envir/

### ISSUE THREAD

**Issue by larsks** [redhat-openstack/tripleo-quickstart#49]
Need to update http://blog.oddbit.com/2016/02/19/deploy-an-ha-openstack-development-envir/ since centosci/minimal.yml changed from a playbook to list of vars to instructions all need updating.

**Comment by trown** [comment]
moved to https://bugs.launchpad.net/tripleo-quickstart/+bug/1571026
