### ISSUE TITLE
jenkins regexp triggers will not trigger for changes to various roles

### ISSUE THREAD

**Issue by larsks** [redhat-openstack/tripleo-quickstart#50]
Our gate jobs have a regexp trigger that looks like:

```
playbooks/roles/(libvirt|common|overcloud|provision|rebuild-inventory|tripleo)/.*
```

That will miss -- for example -- `environment`, and `parts`.  We can add those two, or consider just matching on `playbooks/roles/.*` instead.

**Comment by trown** [comment]
resolved by https://github.com/redhat-openstack/tripleo-quickstart/commit/389d2e9af6eb3fa00fc5096246de33b71279e3a5
