### ISSUE TITLE
improve documentation for tags

### ISSUE THREAD

**Issue by halcyondude** [redhat-openstack/tripleo-quickstart#54]
The addition of tags is super useful and totally the right thing to do (thanks!)

That said, to a oooq newcomer (we want these folks!) - from ./quickstart.sh --help, it's clear that we have tags, but we don't tell folks what they are.  If they dig into the .sh, or walk through the playbooks (and know what to look for) that are "discoverable" - but it would make sense to have --help list the available tags.  I realize that static text for --help causes a _potential_ drift issue later on.  IMHO what would be ideal is if the tags found in playbooks could be dynamically discovered and listed...but that's getting perhaps too elaborate and not pragmatically worth the effort. This issue is just to capture the idea, not infer a solution.  

Somewhere between docs, --help, and [uber solution] we should be able to find something workable.

**Comment by trown** [comment]
moved to https://bugs.launchpad.net/tripleo-quickstart/+bug/1571022
