### ISSUE TITLE
less friction: provide summary / visualization of what quickstart deployed as artifacts

### ISSUE THREAD

**Issue by halcyondude** [redhat-openstack/tripleo-quickstart#55]
new feature: after tripleo-quickstart deploys overcloud, it would be super-cool to provide the (hopefully new) user with artifacts (textual summary, diagram, ___) that illustrate _what just happened_.  One of the principal benefits is the streamlining of deploying everything by hand.  To the experienced user, this benefit is obvious, and to find specific info on topology, services/endpoints deployed, etc is also simple...it's a quick jaunt to look in a file, or execute a CLI command.  

That said, to someone new to OpenStack or TripleO the jaunt is daunting.  Even figuring out how to pull up the horizon/dashboard could be difficult, and figuring out what went right (or worse...what went wrong) is quite a bit more difficult.  This might be projecting my own [recent] experience but it's germaine.  To addess this, I propose some combination of:
1. Use @larsks python scripts that generate diagrams of heat templates / stacks deployed, networking topology, etc.  Anything that quickly will illustrate what was just deployed.  IMHO this fits very well with the declarative nature of Ansible (e.g. "I told quickstart to deploy __ (topology)**, now I have this __(diagrams)**.  
2. Do something similar to: https://github.com/redhat-openstack/khaleesi/commit/0f5197f92f2fc01fc1f35a11d68774f3c80f7dac - This adds aliases to ssh.config.ansible to create/nuke SSH tunnels that map local ports --> :80 on the undercloud.  Add one for overcloud (if deployed).  This would make it simple for a new user (or anyone) to access the dashboard via a local port.

Additional ideas that reduce the impediments to adoption (friction) of quickstart as a mechanism to streamline dev/test/discovery are probably not hard to conjure up.  

Thoughts?

**Comment by larsks** [comment]
I think there are too many issues here.  Number 2, which is bascially "provider access to overcloud services", should be it's own issue and is definitely something we need.  There was some discussion on that topic at the bootcamp this week, and also on `#tripleo` just earlier this morning.

I opened #56 on this topic.

I like the idea of  roles that can provide friendly details about the deployed environment.

**Comment by halcyondude** [comment]
Apologies for conflation.  Agreed we should decouple.

**Comment by trown** [comment]
This one is a bit complicated to directly transfer to https://bugs.launchpad.net/tripleo-quickstart

Please open specific RFE's there.
