### ISSUE TITLE
Provide (remote) access to overcloud services

### ISSUE THREAD

**Issue by larsks** [redhat-openstack/tripleo-quickstart#56]
Our current quickstart deployments leave the overcloud largely inaccessible.  We need an easy path from "deploy using quickstart" to "accessing overcloud services" that doesn't involve manually sshing into the undercloud.

**Comment by larsks** [comment]
@halcyondude suggested in #55:

> Do something similar to: redhat-openstack/khaleesi@0f5197f - This adds aliases to ssh.config.ansible to create/nuke SSH tunnels that map local ports --> :80 on the undercloud. Add one for overcloud (if deployed). This would make it simple for a new user (or anyone) to access the dashboard via a local port.

**Comment by admiyo** [comment]
The overcloud should be exposed to people other than the original developer. The ssh tunnel approach makes that hard to collaborate.  Suggest that we add an inactive interface for the external network on the controller that can be activated after the deploy is completed.

**Comment by trown** [comment]
Moved to https://bugs.launchpad.net/tripleo-quickstart/+bug/1564946
