### ISSUE TITLE
ansible error: The `libvirt` module is not importable

### ISSUE THREAD

**Issue by EmilienM** [redhat-openstack/tripleo-quickstart#61]
By default on fresh Centos7, some packages are missing:
- libvirt-python
- python-lxml
- libvirt

**Comment by EmilienM** [comment]
so if I install libvirt-python on the remote host, I go further but still failing:
FAILED! => {"changed": false, "failed": true, "msg": "The `lxml` module is not importable. Check the requirements."}

**Comment by EmilienM** [comment]
last comment is solved by installing python-lxml on the remote host.

**Comment by trown** [comment]
whoops, we broke the default tags today...

https://review.gerrithub.io/270276 will fix it.

**Comment by EmilienM** [comment]
Thanks!
