### ISSUE TITLE
Ironic pxe_ssh driver configuration happens too late

### ISSUE THREAD

**Issue by trown** [redhat-openstack/tripleo-quickstart#65]
We are using qemu://session to manage the overcloud VMs, which requires a change to the Ironic pxe_ssh driver configuration[1]. However, by doing this in the undercloud-install.sh script, we break someone following the instructions to "Run `openstack undercloud install`, then follow upstream instructions."[2]

Instead, we should do this ironic configuration at the end of the libvirt role, so that the alternative instructions work again.

[1] https://github.com/redhat-openstack/tripleo-quickstart/blob/master/playbooks/roles/tripleo/undercloud/templates/undercloud-install.sh.j2#L10-L17
[2] https://www.redhat.com/archives/rdo-list/2016-March/msg00171.html

**Comment by trown** [comment]
The fact that we are defaulting the libvirt_uri var in the libvirt role[1], but using it in the tripleo/undercloud role is further evidence we are doing it in the wrong place.

[1] https://github.com/redhat-openstack/tripleo-quickstart/blob/master/playbooks/roles/libvirt/defaults/main.yml

**Comment by larsks** [comment]
We need this value in both the libvirt role and in the undercloud configuration.  If we're planning on moving the tripleo/\* roles out of tripleo-quickstart, this suggests that the libvirt/\* roles _are_ the right place for it...and we _also_ need the same setting in tripleo/undercloud.

Does that make sense?

**Comment by trown** [comment]
Actually, after moving the ironic config step in https://review.gerrithub.io/#/c/270892 we no longer use libvirt_uri outside of the libvirt roles.
