### ISSUE TITLE
undercloud.qcow2.md5 should not contain absolute path

### ISSUE THREAD

**Issue by judge-red** [redhat-openstack/tripleo-quickstart#7]
As documented at [1], it's a good idea to verify the md5sum of the downloaded undercloud image. However, when executing `md5sum -c undercloud.qcow2.md5`, the check will fail:

[root@rdo mitaka]# md5sum -c undercloud.qcow2.md5
md5sum: /tmp/oooq-images/undercloud.qcow2: No such file or directory
/tmp/oooq-images/undercloud.qcow2: FAILED open or read

This is, because the undercloud.qcow2.md5 file [2] includes an absolute path after the checksum:

6c7dc0e0b14b7b3deff0da284594d778  /tmp/oooq-images/undercloud.qcow2

Instead of just the file name as expected, like this:

6c7dc0e0b14b7b3deff0da284594d778  undercloud.qcow2

---

[1] https://www.rdoproject.org/rdo-manager/
[2] https://ci.centos.org/artifacts/rdo/images/mitaka/delorean/stable/undercloud.qcow2.md5

**Comment by trown** [comment]
proposed fix:
https://review.gerrithub.io/#/c/264886/

**Comment by trown** [comment]
fix merged, but it will take a newly promoted repo in order to get a new md5
