### ISSUE TITLE
Missing /home/stack/tempest/requirements.txt

### ISSUE THREAD

**Issue by jkilpatr** [redhat-openstack/tripleo-quickstart#70]
This seems to be an error in the overcloud-validate.sh script. 

After successfully deploying the overcloud and doing the post install using the provided scripts running the overcloud validate on a CentOS7 machine gives the following error

```
Could not open requirements file: [Errno 2] No such file or directory: '/home/stack/tempest/requirements.txt'
Command "tools/with_venv.sh pip install --upgrade -r /home/stack/tempest/requirements.txt -r /home/stack/tempest/test-requirements.txt" failed.
```

But only a few lines above in standard out we can see the script doing this. 

```
rm -rf /home/stack/tempest
mkdir /home/stack/tempest
cd /home/stack/tempest
```

Which would remove the requirements.txt even if it was generated properly in the first place.

**Comment by sshnaidm** [comment]
@jkilpatr it's bug in RDO tempest: https://bugzilla.redhat.com/show_bug.cgi?id=1344339

**Comment by jkilpatr** [comment]
thanks for letting me know, I'll monitor it over there.
