### ISSUE TITLE
When the undercloud vm is already running, quickstart fails

### ISSUE THREAD

**Issue by mbaldessari** [redhat-openstack/tripleo-quickstart#9]
Just noticed that if the undercloud vm is already running (because of a previously failed job or for some whatever reason), the deployment bails out with:
TASK [setup/undercloud : start undercloud vm] **********************************
Thursday 03 March 2016  10:31:40 -0500 (0:00:00.516)       0:03:31.308 *******\* 
failed: [host0] => (item={u'flavor': u'undercloud', u'name': u'undercloud'}) => {"failed": true, "item": {"flavor": "undercloud", "name": "undercloud"}, "msg": "Requested operation is not valid: domain is already running"}

**Comment by trown** [comment]
That shouldn't happen if you use the libvirt/teardown role before the libvirt/setup role, and the quickstart.sh which runs quickstart.yml includes teardown.

Could you provide more details of how you hit this?

**Comment by mbaldessari** [comment]
Oh I see, I think I was following one of the steps in Lars' blog and missed the teardown role. Thanks!
